### ISSUE TITLE
check tigger-lsm packaging

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/tigger-lsm#1]
@gijzelaerr, as discussed, I've split out the Python libraries and standalone scripts into this repo. This should be packaged as ``tigger-lsm`` (contents of bin/) and ``python-tigger-lsm``. I've done basic tests, and this looks to be functional -- could you please do whatever is necessary to get this out the door? If the packaging works, then we can already ship them.

Next in line -- converting the GUI.

**Comment by gijzelaerr** [comment]
The module needs to be renamed to something like `tigger-lsm` also

```
Unpacking python-tigger-lsm (1.4.2-1kern1) ...
dpkg: error processing archive ../python-tigger-lsm_1.4.2-1kern1_amd64.deb (--install):
 trying to overwrite '/usr/lib/python2.7/dist-packages/Tigger/Coordinates.py', which is also in package python-tigger 1.3.10-1kern1
Selecting previously unselected package tigger-lsm.
Preparing to unpack .../tigger-lsm_1.4.2-1kern1_amd64.deb ...
```

**Comment by gijzelaerr** [comment]
checked! all good, uploaded to KERN-3.
