### ISSUE TITLE
ImportError: No module named html.parser

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/tigger-lsm#6]
Getting this error. As near as I can tell, this is because in Python 3 the module has been moved to ``html.parser``. But somehow when I run tigger (using the modernize branch), it gets executed by Python 2. @gijzelaerr help, how do I force it to run in Python 3? How is it even possible that it runs in 2?

**Comment by gijzelaerr** [comment]
we can keep python2 and python3 support

http://python-future.org/compatible_idioms.html#html-parsing

**Comment by gijzelaerr** [comment]
solved
