### ISSUE TITLE
defer import of astropy & co until necessary

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/tigger-lsm#7]
Problem exposed by https://github.com/ska-sa/meqtrees-cattery/issues/86

Astropy (at least some versions) uses pkg_resources, which breaks under MeqTrees for reasons unknown.

Since this import is not strictly needed for TiggerSiameseInterface to function, move it from the top level of Coordinates.py to the function where it's actually invoked.

**Comment by gijzelaerr** [comment]
i guess this is solved
